---
linters-settings:
  govet:
    enable:
      - shadow
  gocyclo:
    min-complexity: 42
  cyclop:
    max-complexity: 42
  dupl:
    threshold: 200
  goconst:
    min-len: 2
    min-occurrences: 3
  tagliatelle:
    case:
      rules:
        json: snake
        yaml: snake
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com/tbmatuka/websocket-notify
          - github.com/gorilla/websocket
          - github.com/spf13/cobra
          - golang.org/x/crypto
          - gopkg.in/yaml.v3
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/tbmatuka/websocket-notify)
    custom-order: true

linters:
  enable-all: true
  disable:
    - revive
    - stylecheck
    - wrapcheck
    - nlreturn
    - gomnd
    - mnd
    - wsl
    - whitespace
    - lll
    - nestif
    - funlen
    - paralleltest
    - godot
    - varnamelen
    - ireturn
    - thelper
    - wastedassign
    - goconst
    - gci
    - exhaustruct
    - nonamedreturns
    - interfacebloat
    - dupword
    - forcetypeassert  # tmp needs to be on
    - rowserrcheck  # deprecated
    - sqlclosecheck  # deprecated
    - wastedassign  # deprecated
    - execinquery # deprecated

issues:
  exclude-dirs:
    - test
  exclude-files:
    - ".*_test\\.go$"
